### ISSUE TITLE
Epic: Reach a "Passing" grade for OpenSSF Best Practices Badge Program

### ISSUE THREAD

**Issue by SVendittelli** [SVendittelli/screamer#135]
### User story

As a developer, I want to use bestpractices for open-source projects.

### Details

The [Open Source Security Foundation (OpenSSF)](https://openssf.org/) Best Practices badge is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this web application to explain how they follow each best practice.

See:

- <https://www.bestpractices.dev/en/projects/8226>

### Tasks

- [ ] Create contributing guidelines
- [ ] Start version numbering
- [ ] Generate release notes
- [ ] Measure code coverage
- [ ] Document test policy
- [ ] Consider dynamic analysis tools
