### ISSUE TITLE
Epic: Create a demo of the voting page

### ISSUE THREAD

**Issue by SVendittelli** [SVendittelli/screamer#22]
### User story

As a xxx, I want yyy because zzz.

### Details

Build a demo that users can see and play with without needing to create an account.

### Acceptance criteria

1. Users can swipe through 10 sample movies
2. When they reach the end of the movies, they should be offered a link to the results page (to be built under a separate epic)
3. Users should be able to see the poster, trailer, plot summary, year of release, and categorisation for each movie

### Tasks

- [ ] Create hard-coded sample data to swipe through, these should be the most famous horror movies
- [ ] Create a basic, scrolling interface of the movie details
- [ ] Add swiping to the interface
- [ ] Add a brand moment after the movies have been exhausted
