### ISSUE TITLE
Implement feature flags

### ISSUE THREAD

**Issue by SVendittelli** [SVendittelli/screamer#34]
### User story

As a user, I want to see production ready features because I don't like partially delivered functionality.

### Details

Use [HappyKit](https://happykit.dev/) to manage feature flags on the project.

### Acceptance criteria

1. Have a `beta` feature flag (default `true` in dev and preview, `false` in production) that changes the view the user gets.
2. Have a `tester` trait to opt-in to `beta` features in production.
3. Users on the [beta site](https://beta.halloween.vendittelli.co.uk/) should have the `tester` trait.

### Tasks

- [x] Create [HappyKit](https://happykit.dev/) account
- [x] Create `beta` flag and set it `false` in production and `true` everywhere else
- [ ] Install and configure [@happykit/flags](https://github.com/happykit/flags/tree/master/package)
- [ ] Create [Middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware) to set the `tester` trait to `true` via cookies on the [beta site](https://beta.halloween.vendittelli.co.uk/)
